from . import db
from .models import SeaZoneAdj, SeaZones, Territories, Adjacencies
import random

def randomizer_pop():
    return round(random.uniform(0.6, 1.4)*5072021)


def randomizer_area():
    return round(random.uniform(0.6, 1.4)*38103)


def randomizer_gdp():
    return round(random.uniform(0.6, 1.4)*89827668129)


def randomizer_forts():
    randomInt = random.randint(1, 20)
    if randomInt == 1:
        return 1
    else:
        return 0


def init_territories_random(game_id):
    alaska = Territories(name="Alaska", territory_id=1, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="True", biome="Forest", region="")
    yukon = Territories(name="Yukon", territory_id=2, owner=0, color="gray", game=game_id,  gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="True", biome="Forest", region="")
    nunavut = Territories(name="Nunavut", territory_id=3, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False",coast="True", biome="Forest", region="")
    greenland = Territories(name="Greenland", territory_id=4, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="True", biome="Forest", region="")
    british_columbia = Territories(name="British Columbia", territory_id=5, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="True", biome="Forest", region="")
    alberta = Territories(name="Alberta", territory_id=6, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    saskatchewan = Territories(name="Saskatchewan", territory_id=7, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    ontario = Territories(name="Ontario", territory_id=8, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    quebec = Territories(name="Quebec", territory_id=9, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    newfoundland = Territories(name="Newfoundland", territory_id=10, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    new_england = Territories(name="New England", territory_id=11, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    cascadia = Territories(name="Cascadia", territory_id=12, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    rocky_mountains = Territories(name="Rocky Mountains", territory_id=13, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    nevada = Territories(name="Nevada", territory_id=14, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    alta_california = Territories(name="Alta California", territory_id=15, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    los_angeles = Territories(name="Los Angeles", territory_id=16, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    imperial_valley = Territories(name="Imperial Valley", territory_id=17, owner=0, color="gray", game=game_id, gdp=randomizer_gdp(), area=randomizer_area(), pop=randomizer_pop(), forts=randomizer_forts(), oil="False", uranium="False", gold="False", coast="False", biome="Forest", region="")
    

    db.session.add(alaska)
    db.session.add(yukon)
    db.session.add(nunavut)
    db.session.add(greenland)
    db.session.add(british_columbia)
    db.session.add(alberta)
    db.session.add(saskatchewan)
    db.session.add(ontario)
    db.session.add(quebec)
    db.session.add(newfoundland)
    db.session.add(new_england)
    db.session.add(cascadia)
    db.session.add(rocky_mountains)
    db.session.add(nevada)
    db.session.add(alta_california)
    db.session.add(los_angeles)
    db.session.add(imperial_valley)
    db.session.commit()

    adj_list = []
    adj_list.append(Adjacencies(territory_1 = alaska.id, territory_2 = yukon.id))
    adj_list.append(Adjacencies(territory_1 = alaska.id, territory_2 = british_columbia.id))
    adj_list.append(Adjacencies(territory_1 = yukon.id, territory_2 = nunavut.id))
    adj_list.append(Adjacencies(territory_1 = yukon.id, territory_2 = british_columbia.id))
    adj_list.append(Adjacencies(territory_1 = yukon.id, territory_2 = alberta.id))
    adj_list.append(Adjacencies(territory_1 = yukon.id, territory_2 = saskatchewan.id))
    adj_list.append(Adjacencies(territory_1 = nunavut.id, territory_2 = saskatchewan.id))
    adj_list.append(Adjacencies(territory_1 = british_columbia.id, territory_2 = alberta.id))
    adj_list.append(Adjacencies(territory_1 = british_columbia.id, territory_2 = cascadia.id))
    adj_list.append(Adjacencies(territory_1 = british_columbia.id, territory_2 = rocky_mountains.id))
    adj_list.append(Adjacencies(territory_1 = alberta.id, territory_2 = rocky_mountains.id))
    adj_list.append(Adjacencies(territory_1 = alberta.id, territory_2 = saskatchewan.id))
    adj_list.append(Adjacencies(territory_1 = saskatchewan.id, territory_2 = ontario.id))
    adj_list.append(Adjacencies(territory_1 = saskatchewan.id, territory_2 = rocky_mountains.id))
    adj_list.append(Adjacencies(territory_1 = ontario.id, territory_2 = quebec.id))
    adj_list.append(Adjacencies(territory_1 = ontario.id, territory_2 = newfoundland.id))
    adj_list.append(Adjacencies(territory_1 = quebec.id, territory_2 = newfoundland.id))
    adj_list.append(Adjacencies(territory_1 = quebec.id, territory_2 = new_england.id))
    adj_list.append(Adjacencies(territory_1 = newfoundland.id, territory_2 = new_england.id))
    adj_list.append(Adjacencies(territory_1 = cascadia.id, territory_2 = rocky_mountains.id))
    adj_list.append(Adjacencies(territory_1 = cascadia.id, territory_2 = nevada.id))
    adj_list.append(Adjacencies(territory_1 = rocky_mountains.id, territory_2 = nevada.id))
    adj_list.append(Adjacencies(territory_1 = alta_california.id, territory_2 = nevada.id))
    adj_list.append(Adjacencies(territory_1 = alta_california.id, territory_2 = los_angeles.id))
    adj_list.append(Adjacencies(territory_1 = los_angeles.id, territory_2 = imperial_valley.id))
    adj_list.append(Adjacencies(territory_1 = rocky_mountains.id, territory_2 = nevada.id))
    for item in adj_list:
        db.session.add(item)

    sea_zone_list = []
    sea_zone_list.append(SeaZones(name="Baltic Sea", time=70, game=game_id))
    sea_zone_list.append(SeaZones(name="North Sea", time=75, game=game_id))
    sea_zone_list.append(SeaZones(name="Norwegian Sea", time=95, game=game_id))
    sea_zone_list.append(SeaZones(name="Bay of Biscay", time=95, game=game_id))
    sea_zone_list.append(SeaZones(name="Western Mediterranean", time=70, game=game_id))
    sea_zone_list.append(SeaZones(name="Eastern Mediterranean", time=50, game=game_id))
    sea_zone_list.append(SeaZones(name="Labrador Sea", time=150, game=game_id))
    sea_zone_list.append(SeaZones(name="Baffin Bay", time=180, game=game_id))
    sea_zone_list.append(SeaZones(name="Arctic Ocean", time=180, game=game_id))
    sea_zone_list.append(SeaZones(name="St. Lawrence", time=120, game=game_id))
    sea_zone_list.append(SeaZones(name="Grand Banks", time=130, game=game_id))
    sea_zone_list.append(SeaZones(name="Eastern Seaboard", time=145, game=game_id))
    sea_zone_list.append(SeaZones(name="Gulf of Mexico", time=60, game=game_id))
    sea_zone_list.append(SeaZones(name="Caribbean Sea", time=110, game=game_id))
    sea_zone_list.append(SeaZones(name="Macronesia", time=140, game=game_id))
    sea_zone_list.append(SeaZones(name="Central Atlantic Ocean", time=250, game=game_id))
    sea_zone_list.append(SeaZones(name="Gulf of Guinea", time=180, game=game_id))
    sea_zone_list.append(SeaZones(name="South Atlantic Ocean", time=225, game=game_id))
    sea_zone_list.append(SeaZones(name="Scotia", time=90, game=game_id))
    sea_zone_list.append(SeaZones(name="Red Sea", time=80, game=game_id))
    sea_zone_list.append(SeaZones(name="Persian Gulf", time=40, game=game_id))
    sea_zone_list.append(SeaZones(name="Arabian Sea", time=150, game=game_id))
    sea_zone_list.append(SeaZones(name="Bay of Bengal", time=135, game=game_id))
    sea_zone_list.append(SeaZones(name="Indian Ocean", time=380, game=game_id))
    sea_zone_list.append(SeaZones(name="Bering Sea", time=110, game=game_id))
    sea_zone_list.append(SeaZones(name="Sea of Japan", time=90, game=game_id))
    sea_zone_list.append(SeaZones(name="East China Sea", time=85, game=game_id))
    sea_zone_list.append(SeaZones(name="South China Sea", time=105, game=game_id))
    sea_zone_list.append(SeaZones(name="Java Sea", time=165, game=game_id))
    sea_zone_list.append(SeaZones(name="Philippine Sea", time=210, game=game_id))
    sea_zone_list.append(SeaZones(name="Coral Sea", time=270, game=game_id))
    sea_zone_list.append(SeaZones(name="North Pacific Ocean", time=405, game=game_id))
    sea_zone_list.append(SeaZones(name="Polynesia", time=250, game=game_id))
    sea_zone_list.append(SeaZones(name="Central Pacific Ocean", time=240, game=game_id))
    sea_zone_list.append(SeaZones(name="Southern Ocean", time=250, game=game_id))
    sea_zone_list.append(SeaZones(name="South Pacific Ocean", time=270, game=game_id))
    sea_zone_list.append(SeaZones(name="Mozambique Strait", time=105, game=game_id))
    sea_zone_list.append(SeaZones(name="Gulf of California", time=120, game=game_id))
    for item in sea_zone_list:
        db.session.add(item)
    sea_adj = []
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[0].id, sea_zone2=sea_zone_list[1].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[1].id, sea_zone2=sea_zone_list[2].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[1].id, sea_zone2=sea_zone_list[3].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[2].id, sea_zone2=sea_zone_list[8].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[2].id, sea_zone2=sea_zone_list[6].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[3].id, sea_zone2=sea_zone_list[6].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[3].id, sea_zone2=sea_zone_list[10].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[3].id, sea_zone2=sea_zone_list[14].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[4].id, sea_zone2=sea_zone_list[5].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[4].id, sea_zone2=sea_zone_list[14].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[6].id, sea_zone2=sea_zone_list[10].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[6].id, sea_zone2=sea_zone_list[9].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[6].id, sea_zone2=sea_zone_list[7].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[7].id, sea_zone2=sea_zone_list[8].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[7].id, sea_zone2=sea_zone_list[24].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[8].id, sea_zone2=sea_zone_list[24].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[9].id, sea_zone2=sea_zone_list[10].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[10].id, sea_zone2=sea_zone_list[11].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[10].id, sea_zone2=sea_zone_list[15].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[10].id, sea_zone2=sea_zone_list[14].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[11].id, sea_zone2=sea_zone_list[12].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[11].id, sea_zone2=sea_zone_list[13].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[11].id, sea_zone2=sea_zone_list[15].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[12].id, sea_zone2=sea_zone_list[13].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[14].id, sea_zone2=sea_zone_list[15].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[14].id, sea_zone2=sea_zone_list[16].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[15].id, sea_zone2=sea_zone_list[16].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[15].id, sea_zone2=sea_zone_list[17].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[16].id, sea_zone2=sea_zone_list[17].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[17].id, sea_zone2=sea_zone_list[18].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[17].id, sea_zone2=sea_zone_list[36].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[17].id, sea_zone2=sea_zone_list[34].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[18].id, sea_zone2=sea_zone_list[33].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[19].id, sea_zone2=sea_zone_list[21].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[20].id, sea_zone2=sea_zone_list[21].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[21].id, sea_zone2=sea_zone_list[22].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[21].id, sea_zone2=sea_zone_list[36].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[21].id, sea_zone2=sea_zone_list[23].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[22].id, sea_zone2=sea_zone_list[23].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[22].id, sea_zone2=sea_zone_list[28].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[23].id, sea_zone2=sea_zone_list[34].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[24].id, sea_zone2=sea_zone_list[25].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[24].id, sea_zone2=sea_zone_list[29].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[24].id, sea_zone2=sea_zone_list[31].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[24].id, sea_zone2=sea_zone_list[37].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[25].id, sea_zone2=sea_zone_list[26].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[25].id, sea_zone2=sea_zone_list[29].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[26].id, sea_zone2=sea_zone_list[29].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[26].id, sea_zone2=sea_zone_list[27].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[27].id, sea_zone2=sea_zone_list[29].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[27].id, sea_zone2=sea_zone_list[28].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[28].id, sea_zone2=sea_zone_list[29].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[28].id, sea_zone2=sea_zone_list[30].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[29].id, sea_zone2=sea_zone_list[30].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[29].id, sea_zone2=sea_zone_list[31].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[30].id, sea_zone2=sea_zone_list[31].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[30].id, sea_zone2=sea_zone_list[32].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[30].id, sea_zone2=sea_zone_list[34].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[30].id, sea_zone2=sea_zone_list[35].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[31].id, sea_zone2=sea_zone_list[37].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[31].id, sea_zone2=sea_zone_list[32].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[31].id, sea_zone2=sea_zone_list[33].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[32].id, sea_zone2=sea_zone_list[33].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[32].id, sea_zone2=sea_zone_list[35].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[33].id, sea_zone2=sea_zone_list[37].id))
    sea_adj.append(SeaZoneAdj(sea_zone1=sea_zone_list[34].id, sea_zone2=sea_zone_list[35].id))

    db.session.commit()
